### PR TITLE
Updated repo name in slack workflow

### LINKED ISSUE #1: [CI] Update Slack Notification workflow
#### Description
List this repo's name in slack.yml workflow.

### PR DESCRIPTION
**Pull request by shuklaritvik06**
**Description**

This PR fixes #1 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by s1ntaxe770r** [comment]
Hey @shuklaritvik06  thanks for the contribution , looks like you have an unsigned commit kindly, kindly sign off using the steps [here](https://github.com/layer5io/meshery-smp-performance-action/pull/3/checks?check_run_id=3148567119) and it should be ready to merge

**Comment by shuklaritvik06** [comment]
> Hey @shuklaritvik06 thanks for the contribution , looks like you have an unsigned commit kindly, kindly sign off using the steps [here](https://github.com/layer5io/meshery-smp-performance-action/pull/3/checks?check_run_id=3148567119) and it should be ready to merge

Thanks for the help , but when i'm cloning this repo on my local system the .github folder is not showing and the slack.yml file is in that folder only, please help me how i can clone that folder as i have to use the git command to signoff my commits?

**Comment by DelusionalOptimist** [comment]
hey @shuklaritvik06 that's happening because filenames/dirnames starting with `.` are treated as hidden.
You can make your changes and add them using `git add .github`
Then proceed to commit them using the steps that @s1ntaxe770r has pointed out. : )

**Comment by shuklaritvik06** [comment]
> hey @shuklaritvik06 that's happening because filenames/dirnames starting with `.` are treated as hidden.
> You can make your changes and add them using `git add .github`
> Then proceed to commit them using the steps that @s1ntaxe770r has pointed out. : )

Thank you @DelusionalOptimist  :) Now it's fine?

**Review by s1ntaxe770r — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, gents

**Pull request merged**
